version: '3'
services:
  mongopruebaborja: 
    build: ./mongoData/
    image: borjaortizllamas/mongopruebaborja
  springbootpruebaborja: 
    build: ./appClients/
    image: borjaortizllamas/springbootpruebaborja
    ports:
      - "8080:8080"
    depends_on:
      - mongopruebaborja